[package]
name = "tinypatscan"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = {version = "1.10.0", optional = true }
wide = { version = "0.7.32", optional = true }

[features]
multithreading = ["dep:rayon", "std"]
simd = ["dep:wide"]
std = []
default = ["simd"]
